version: '3.8'

# Minimal Standalone Docker Compose for Interactive World News Map
# This configuration uses only Docker images - no additional files needed
# Usage: docker-compose -f docker-compose.minimal-standalone.yml up -d

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: news-map-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-news_map_db}
      POSTGRES_USER: ${POSTGRES_USER:-news_map_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_this_password}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - news-map-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-news_map_user} -d ${POSTGRES_DB:-news_map_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    security_opt:
      - no-new-privileges:true

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: news-map-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-change_this_password} --appendonly yes --appendfsync everysec
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - news-map-network
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD:-change_this_password}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    security_opt:
      - no-new-privileges:true

  # Backend API (Pre-built image from GitHub Container Registry)
  backend:
    image: ghcr.io/kingkhan92/interactive-world-news-map-backend:latest
    container_name: news-map-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://${POSTGRES_USER:-news_map_user}:${POSTGRES_PASSWORD:-change_this_password}@postgres:5432/${POSTGRES_DB:-news_map_db}
      REDIS_URL: redis://:${REDIS_PASSWORD:-change_this_password}@redis:6379
      JWT_SECRET: ${JWT_SECRET:-change-this-to-a-very-secure-secret-at-least-32-characters}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-24h}
      NEWS_API_KEY: ${NEWS_API_KEY}
      GUARDIAN_API_KEY: ${GUARDIAN_API_KEY}
      GEOCODING_API_KEY: ${GEOCODING_API_KEY}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      RATE_LIMIT_WINDOW_MS: ${RATE_LIMIT_WINDOW_MS:-900000}
      RATE_LIMIT_MAX_REQUESTS: ${RATE_LIMIT_MAX_REQUESTS:-100}
      # Database Migration
      RUN_MIGRATIONS: ${RUN_MIGRATIONS:-true}
      # LLM Provider Configuration
      BIAS_ANALYSIS_PROVIDER: ${BIAS_ANALYSIS_PROVIDER:-openai}
      BIAS_ANALYSIS_FALLBACK_PROVIDERS: ${BIAS_ANALYSIS_FALLBACK_PROVIDERS:-openai,grok}
      # OpenAI Configuration
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-3.5-turbo}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-https://api.openai.com/v1}
      OPENAI_TIMEOUT: ${OPENAI_TIMEOUT:-30000}
      OPENAI_MAX_RETRIES: ${OPENAI_MAX_RETRIES:-3}
      OPENAI_RATE_LIMIT: ${OPENAI_RATE_LIMIT:-60}
      # Grok Configuration
      GROK_API_KEY: ${GROK_API_KEY}
      GROK_MODEL: ${GROK_MODEL:-grok-beta}
      GROK_BASE_URL: ${GROK_BASE_URL:-https://api.x.ai/v1}
      GROK_TIMEOUT: ${GROK_TIMEOUT:-30000}
      GROK_MAX_RETRIES: ${GROK_MAX_RETRIES:-3}
      GROK_RATE_LIMIT: ${GROK_RATE_LIMIT:-60}
      # External Ollama Configuration (if using external Ollama instance)
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://host.docker.internal:11434}
      OLLAMA_MODEL: ${OLLAMA_MODEL:-llama2:7b}
      OLLAMA_TIMEOUT: ${OLLAMA_TIMEOUT:-60000}
      OLLAMA_MAX_RETRIES: ${OLLAMA_MAX_RETRIES:-2}
      OLLAMA_RATE_LIMIT: ${OLLAMA_RATE_LIMIT:-30}
      # LLM Health Check Configuration
      LLM_HEALTH_CHECK_INTERVAL: ${LLM_HEALTH_CHECK_INTERVAL:-300000}
      LLM_ENABLE_FAILOVER: ${LLM_ENABLE_FAILOVER:-true}
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    volumes:
      - backend_logs:/app/logs
    networks:
      - news-map-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Frontend React App (Pre-built image from GitHub Container Registry)
  frontend:
    image: ghcr.io/kingkhan92/interactive-world-news-map-frontend:latest
    container_name: news-map-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3001}
      VITE_SOCKET_URL: ${VITE_SOCKET_URL:-http://localhost:3001}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    networks:
      - news-map-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

networks:
  news-map-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  backend_logs:
    driver: local